# -*- coding: utf-8 -*-
# Generated by Django 1.11.11 on 2019-03-12 05:16
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('offerride', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Ride',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('startpoint', models.CharField(max_length=250)),
                ('endpoint', models.CharField(max_length=250)),
                ('ipoint1', models.CharField(max_length=250)),
                ('ipoint2', models.CharField(max_length=250)),
                ('driver', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='offerride.Driver')),
            ],
        ),
    ]
