# -*- coding: utf-8 -*-
# Generated by Django 1.11.11 on 2019-03-12 05:21
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('offerride', '0002_ride'),
    ]

    operations = [
        migrations.AddField(
            model_name='ride',
            name='date',
            field=models.CharField(default=b'23/3/2019', max_length=250),
        ),
    ]
