# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2019-03-16 04:32
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('offerride', '0006_auto_20190315_1215'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ride',
            name='date',
            field=models.CharField(default='23/3/2019', max_length=250),
        ),
        migrations.AlterField(
            model_name='ride',
            name='time',
            field=models.CharField(default='10:10', max_length=250),
        ),
        migrations.AlterField(
            model_name='ride',
            name='username',
            field=models.CharField(default='rnk', max_length=250),
        ),
    ]
