# -*- coding: utf-8 -*-
# Generated by Django 1.11.11 on 2019-03-16 16:03
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('offerride', '0009_auto_20190316_1037'),
    ]

    operations = [
        migrations.AddField(
            model_name='car',
            name='username',
            field=models.CharField(default=b'rnk', max_length=250),
        ),
    ]
