# -*- coding: utf-8 -*-
# Generated by Django 1.11.11 on 2019-03-16 21:55
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('offerride', '0010_car_username'),
    ]

    operations = [
        migrations.CreateModel(
            name='book',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(default=b'rnk', max_length=250)),
                ('ride_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='offerride.Ride')),
            ],
        ),
    ]
