# -*- coding: utf-8 -*-
# Generated by Django 1.11.11 on 2019-03-17 01:05
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('offerride', '0011_book'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='book',
            name='ride_id',
        ),
        migrations.DeleteModel(
            name='book',
        ),
    ]
